### ISSUE TITLE
should we add a writable overlay to the containers?

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurocommand#100]
https://sylabs.io/guides/3.5/user-guide/persistent_overlays.html

**Comment by civier** [comment]
Would be definitely useful as an option, although nobody came to me with
this requirement till now.
More urgent will be to have an overlay (or whatever the equivalent in the
docker world is) for Neuromachine. This way, advanced users can install
software manually, and take the updated container with them to another
platform.

Any thoughts?

**Comment by stebo85** [comment]
A writable overlay is not possible for Docker as far as I know - only for singularity. I also thought about it more and think we definitely should NOT do this, as a writable overlay defeats the purpose of the project as it would make the environment not reproducible.

**Comment by civier** [comment]
I do not completely agree, because I think that also expert users should be
able to use VNM, and they often need to install additional software (we
don't want to force them to learn how to build containers, or to be a
bottleneck ourselves). So an option to take the VNM that was used for the
analysis (with any changes made) would be useful. It is true that most of
the software is in containers anyway, but things like environment
variables/etc. can have influence -- for example, a lot of software save
configuration files in the home directory of the user, and this will be
kept within the VNM.
Should I add it for the agenda of our next meeting?

**Comment by stebo85** [comment]
Dear @civier 

An expert user can simply write a script that performs the modifications. This would then also be reproducible. No need to add to the agenda.

Kind regards
Steffen
