### ISSUE TITLE
deduplication

### ISSUE THREAD

**Issue by yarikoptic** [NeuroDesk/neurocommand#111]
just listened to the talk during OHBM 2022 brainhack.  you have mentioned that you use deduplication filesystem, but I have missed exact name.  Was it the https://github.com/opendedup/sdfs ? or https://github.com/cvmfs/cvmfs ? or ... ?

I wondered if you compared to other solutions?  E.g. in my case I am a big fan of BTRFS due to its efficient operation with git-annex (https://www.datalad.org/test_fs_analysis.html) and CoW functionality.  Apparently it also has support for deduplication (https://btrfs.wiki.kernel.org/index.php/Deduplication) which I have not tried yet, but curious if someone else did ;)

**Comment by stebo85** [comment]
Dear @yarikoptic,

we use CVMFS because in addition to the deduplication we need to bring it to the end-user via HTTP. I am not aware of any other filesystems that can do that :)

big fan of BTRFS as well - I run this on my NAS at home and love it (the love started after it got mature enough :D - the beginnings were less lovely)

Thank you
Cheers
Steffen
